services:
  app:
    image: ghcr.io/prabesh01/ratta:latest
    restart: unless-stopped
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./.env:/app/.env
    ports:
      - "127.0.0.1:8855:8855"

