# Generated by Django 5.2.1 on 2026-03-17 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='section',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GroupCousework',
            fields=[
                ('gcid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.module')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_for', models.CharField(blank=True, choices=[('coding', 'Coding vyaidinxu solo'), ('documentation', 'Documentation vyaidinxu solo'), ('frontend', 'Frontend matrai'), ('backend', 'Backend matrai'), ('cant', 'kei ni aaudena ;/ need help'), ('wont', 'kei garna vyaidina hola. team ma rakho'), ('partial_coding', 'halka coding assist'), ('partial_documentation', 'Halka documentation assist'), ('partial_all', 'alikiti sab ma help garxu')], null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_coursework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groupcousework')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('looking_for', models.CharField(blank=True, choices=[('coding', 'Coding vyaidinxu solo'), ('documentation', 'Documentation vyaidinxu solo'), ('frontend', 'Frontend matrai'), ('backend', 'Backend matrai'), ('cant', 'kei ni aaudena ;/ need help'), ('wont', 'kei garna vyaidina hola. team ma rakho'), ('partial_coding', 'halka coding assist'), ('partial_documentation', 'Halka documentation assist'), ('partial_all', 'alikiti sab ma help garxu')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group_coursework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.groupcousework')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, choices=[('coding', 'Coding vyaidinxu solo'), ('documentation', 'Documentation vyaidinxu solo'), ('frontend', 'Frontend matrai'), ('backend', 'Backend matrai'), ('cant', 'kei ni aaudena ;/ need help'), ('wont', 'kei garna vyaidina hola. team ma rakho'), ('partial_coding', 'halka coding assist'), ('partial_documentation', 'Halka documentation assist'), ('partial_all', 'alikiti sab ma help garxu')], null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
