# Generated by Django 5.2.1 on 2026-03-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_section_groupcousework_designation_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
