# Generated by Django 5.2.1 on 2026-03-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='open_for',
            field=models.CharField(blank=True, choices=[('coding', 'Coding vyaidinxu solo'), ('documentation', 'Documentation vyaidinxu solo'), ('frontend', 'Frontend matrai'), ('backend', 'Backend matrai'), ('cant', 'kei ni aaudena ;/ need help'), ('passive', 'kei garna vyaidina hola. team ma rakho'), ('coding_assist', 'halka coding assist'), ('documentation_assist', 'Halka documentation assist'), ('overall_assist', 'alikiti sab ma help garxu'), ('emotional_support', 'Vibe Manager + Coke/Momo sponsor')], null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('coding', 'Coding vyaidinxu solo'), ('documentation', 'Documentation vyaidinxu solo'), ('frontend', 'Frontend matrai'), ('backend', 'Backend matrai'), ('cant', 'kei ni aaudena ;/ need help'), ('passive', 'kei garna vyaidina hola. team ma rakho'), ('coding_assist', 'halka coding assist'), ('documentation_assist', 'Halka documentation assist'), ('overall_assist', 'alikiti sab ma help garxu'), ('emotional_support', 'Vibe Manager + Coke/Momo sponsor')], null=True),
        ),
        migrations.AlterField(
            model_name='teammembership',
            name='position',
            field=models.CharField(blank=True, choices=[('coding', 'Coding vyaidinxu solo'), ('documentation', 'Documentation vyaidinxu solo'), ('frontend', 'Frontend matrai'), ('backend', 'Backend matrai'), ('cant', 'kei ni aaudena ;/ need help'), ('passive', 'kei garna vyaidina hola. team ma rakho'), ('coding_assist', 'halka coding assist'), ('documentation_assist', 'Halka documentation assist'), ('overall_assist', 'alikiti sab ma help garxu'), ('emotional_support', 'Vibe Manager + Coke/Momo sponsor')], null=True),
        ),
    ]
