# Generated by Django 5.2.1 on 2026-03-24 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_designation_open_for_alter_team_looking_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
